### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by septagram** [amireh/guide.js#6]
I'd love to see a working demo of this library (or a sample website using it) before committing to it. Is there any?

**Comment by amireh** [comment]
Hey, I've set up a small server that serves the examples (they need Ruby to run) which you can view here: http://guide-js.amireh.net/

Please keep in mind that I'm not actively maintaining this library, but I'd be happy to help if you find any issues.

**Comment by septagram** [comment]
Thanks :)
